package com.rork.neonhighwayracer

object Config {
    const val EXPO_PUBLIC_PROJECT_ID = ""
    const val EXPO_PUBLIC_RORK_API_BASE_URL = ""
    const val EXPO_PUBLIC_RORK_AUTH_URL = ""
    const val EXPO_PUBLIC_RORK_FUNCTIONS_URL = ""
    const val EXPO_PUBLIC_RORK_TOOLKIT_SECRET_KEY = ""
    const val EXPO_PUBLIC_TEAM_ID = ""
    const val EXPO_PUBLIC_TOOLKIT_URL = ""

    val allValues: Map<String, String> = mapOf(
        "EXPO_PUBLIC_PROJECT_ID" to EXPO_PUBLIC_PROJECT_ID,
        "EXPO_PUBLIC_RORK_API_BASE_URL" to EXPO_PUBLIC_RORK_API_BASE_URL,
        "EXPO_PUBLIC_RORK_AUTH_URL" to EXPO_PUBLIC_RORK_AUTH_URL,
        "EXPO_PUBLIC_RORK_FUNCTIONS_URL" to EXPO_PUBLIC_RORK_FUNCTIONS_URL,
        "EXPO_PUBLIC_RORK_TOOLKIT_SECRET_KEY" to EXPO_PUBLIC_RORK_TOOLKIT_SECRET_KEY,
        "EXPO_PUBLIC_TEAM_ID" to EXPO_PUBLIC_TEAM_ID,
        "EXPO_PUBLIC_TOOLKIT_URL" to EXPO_PUBLIC_TOOLKIT_URL,
    )
}
